# Generated by Django 4.2.6 on 2023-10-22 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.crypto
import django.utils.timezone
import functools
import utils.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('uid', models.CharField(default=functools.partial(django.utils.crypto.get_random_string, *(), **{'allowed_chars': '0123456789', 'length': 6}), max_length=6, primary_key=True, serialize=False, verbose_name='uid')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(max_length=150, verbose_name='last name')),
                ('middle_name', models.CharField(blank=True, max_length=150, verbose_name='middle name')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('code', models.CharField(default=utils.utils.get_uuid_hex, max_length=32, primary_key=True, serialize=False, verbose_name='code')),
                ('name', models.CharField(max_length=12, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, max_length=256, verbose_name='description')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('mate1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_teams', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
                ('mate2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mated_teams', to=settings.AUTH_USER_MODEL, verbose_name='member')),
            ],
            options={
                'verbose_name': 'team',
                'verbose_name_plural': 'teams',
                'unique_together': {('mate1', 'mate2')},
            },
        ),
    ]
