# Generated by Django 4.2.6 on 2023-10-22 06:35

from django.db import migrations, models
import django.db.models.deletion
import utils.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('code', models.CharField(default=utils.utils.get_uuid_hex, max_length=32, primary_key=True, serialize=False, verbose_name='code')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'scheduled'), (1, 'ongoing'), (2, 'finished'), (3, 'walk-over')], default=0, verbose_name='status')),
                ('score1', models.PositiveSmallIntegerField(default=None, help_text='The None value means that match hast not been finished.', null=True, verbose_name='participant1 match score')),
                ('score2', models.PositiveSmallIntegerField(default=None, help_text='The None value means that match hast not been finished.', null=True, verbose_name='participant2 match score')),
                ('finish', models.DateTimeField(default=None, null=True, verbose_name='finish date')),
                ('participant1', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='participated1', to='account.team', verbose_name='team as participant-1')),
                ('participant2', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='participated2', to='account.team', verbose_name='team as participant-2')),
            ],
            options={
                'verbose_name': 'match',
                'verbose_name_plural': 'matches',
                'ordering': ['status', '-finish'],
            },
        ),
    ]
